# Generated by Django 2.2 on 2021-04-22 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0002_auto_20210308_1327'),
    ]

    operations = [
        migrations.CreateModel(
            name='factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('rif', models.CharField(max_length=150, verbose_name='RIF')),
                ('razon', models.CharField(max_length=150, verbose_name='Razón Social')),
                ('nfactura', models.IntegerField(verbose_name='Número de Factura')),
                ('ncontrol', models.IntegerField(verbose_name='Número de Control')),
                ('fechafactura', models.DateField(verbose_name='Fecha de Factura')),
                ('fecharecepcion', models.DateField(verbose_name='Fecha de Recepción')),
                ('concepto', models.CharField(max_length=150, verbose_name='Concepto')),
                ('monto', models.DecimalField(decimal_places=5, max_digits=20, verbose_name='Monto')),
                ('iva', models.DecimalField(decimal_places=5, max_digits=20, verbose_name='IVA')),
                ('islr', models.DecimalField(decimal_places=5, max_digits=20, verbose_name='ISLR')),
                ('direccion', models.TextField(verbose_name='Dirección Corporativa')),
                ('estatus', models.CharField(choices=[('R', 'Registrado'), ('S', 'Seleccionado'), ('P', 'Pre-aprobado'), ('A', 'Aprobado')], default='R', max_length=1)),
                ('gerencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.departamento', verbose_name='Gerencia')),
            ],
        ),
    ]
