# Generated by Django 2.2 on 2021-04-23 00:38

from django.db import migrations, models
import pagos.models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to=pagos.models.user_directory_path),
        ),
    ]
