# Generated by Django 2.2 on 2021-04-23 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0002_factura_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='pagos/'),
        ),
    ]
