# Generated by Django 2.2 on 2021-04-23 01:16

from django.db import migrations, models
import pagos.models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0003_auto_20210423_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to=pagos.models.user_directory_path),
        ),
    ]
