# Generated by Django 2.2 on 2021-04-23 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0004_auto_20210423_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='estatus',
            field=models.CharField(choices=[('R', 'Registrada'), ('S', 'Seleccionada'), ('A', 'Aprobada'), ('P', 'Pagada')], default='R', max_length=1),
        ),
    ]
