# Generated by Django 2.2 on 2021-04-27 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0005_auto_20210423_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='estatus',
            field=models.BooleanField(default=False),
        ),
    ]
