# Generated by Django 2.2 on 2021-04-27 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0006_auto_20210427_0104'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='estatus2',
            field=models.BooleanField(default=False),
        ),
    ]
