# Generated by Django 2.2 on 2021-04-29 00:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pagos', '0008_auto_20210428_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='gerencia',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='islr',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='razon',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='rif',
        ),
        migrations.AddField(
            model_name='factura',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='factura',
            name='excento',
            field=models.DecimalField(decimal_places=5, max_digits=20, verbose_name='Excento'),
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('rif', models.CharField(max_length=150, verbose_name='RIF')),
                ('razon', models.CharField(max_length=150, verbose_name='Razón Social')),
                ('clasificacion', models.CharField(choices=[('PNR', 'Persona Natural Residente'), ('PNNR', 'Persona Natural No Residente'), ('PJD', 'Persona Jurídica Domiciliada'), ('PJND', 'Persona Jurídica No Domiciliada'), ('PJNCD', 'Persona Jurídica No Constituida Domiciliada')], default='PNR', max_length=5)),
                ('direccion', models.TextField(verbose_name='Dirección Corporativa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
        migrations.AddField(
            model_name='factura',
            name='empresa',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='pagos.Empresa', verbose_name='Empresa'),
            preserve_default=False,
        ),
    ]
