# Generated by Django 2.2 on 2021-04-29 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0009_auto_20210429_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='rift',
            field=models.CharField(choices=[('V', 'V'), ('E', 'E'), ('P', 'P'), ('J', 'J'), ('G', 'G')], default='J', max_length=1),
        ),
        migrations.AddField(
            model_name='empresa',
            name='tlf',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='direccion',
            field=models.TextField(blank=True, null=True, verbose_name='Dirección Corporativa'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='rif',
            field=models.IntegerField(verbose_name='RIF'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='nfactura',
            field=models.CharField(max_length=150, verbose_name='Número de Factura'),
        ),
    ]
