# Generated by Django 2.2 on 2021-04-29 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0010_auto_20210429_0129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='excento',
        ),
        migrations.AddField(
            model_name='factura',
            name='exento',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=20, verbose_name='Exento'),
            preserve_default=False,
        ),
    ]
