# Generated by Django 2.2 on 2021-04-30 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0012_auto_20210429_0247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='cambiofactura',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True, verbose_name='Cambio Factura'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='cambiopago',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True, verbose_name='Cambio Pago'),
        ),
    ]
