# Generated by Django 2.2 on 2021-04-30 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0013_auto_20210430_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='divisa',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True, verbose_name='A pagar en USD'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='cambiofactura',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True, verbose_name='Tipo de cambio (factura)'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='cambiopago',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True, verbose_name='Tipo de cambio (fecha de pago)'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='islr',
            field=models.DecimalField(decimal_places=5, max_digits=20, verbose_name='ISL'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='retiva',
            field=models.IntegerField(choices=[(75, 75), (100, 100)], default=75, verbose_name='Retención IVA'),
        ),
    ]
