# Generated by Django 2.2 on 2021-04-30 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0015_auto_20210430_0108'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='tiposervicio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='pagos.Islr', verbose_name='Tipo de servicio'),
            preserve_default=False,
        ),
    ]
