# Generated by Django 2.2 on 2021-05-03 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0017_auto_20210430_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='islr',
            name='actividad',
            field=models.CharField(max_length=250, verbose_name='Actividad'),
        ),
    ]
