# Generated by Django 2.2 on 2021-05-04 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0018_auto_20210503_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='ncontrol',
            field=models.CharField(max_length=150, verbose_name='Número de Control'),
        ),
        migrations.AlterField(
            model_name='islr',
            name='sustraendo',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=20, verbose_name='Sustraendo Bs'),
        ),
    ]
