# Generated by Django 2.2 on 2021-05-04 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0019_auto_20210504_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='retiva',
            field=models.IntegerField(choices=[(75, 75), (100, 100)], default=75, verbose_name='Retención IVA'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='retiva',
            field=models.IntegerField(default=75, verbose_name='Retención IVA'),
        ),
    ]
