# Generated by Django 2.2 on 2021-05-04 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20210308_1327'),
        ('pagos', '0020_auto_20210504_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='departamento',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='registration.departamento', verbose_name='Departamento'),
            preserve_default=False,
        ),
    ]
