# Generated by Django 2.2 on 2021-05-05 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0021_factura_departamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='sustraendo',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=20, verbose_name='Sustraendo'),
        ),
    ]
