# Generated by Django 2.2 on 2021-05-05 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0022_factura_sustraendo'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='estatus3',
            field=models.BooleanField(default=False),
        ),
    ]
