# Generated by Django 2.2 on 2021-05-05 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0023_factura_estatus3'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='fechapago',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Pago'),
        ),
        migrations.AddField(
            model_name='factura',
            name='tipo',
            field=models.CharField(choices=[('ser', 'Servicio'), ('alm', 'Compra de almacén'), ('dir', 'Compra directa')], default='ser', max_length=3),
        ),
        migrations.AlterField(
            model_name='factura',
            name='departamento',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='registration.departamento', verbose_name='Departamento'),
        ),
    ]
