# Generated by Django 2.2 on 2021-05-07 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0026_auto_20210507_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='anticipo',
            name='estatus',
            field=models.BooleanField(default=False),
        ),
    ]
