# Generated by Django 2.2 on 2021-05-13 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0028_auto_20210507_0144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anticipo',
            name='cambio',
        ),
        migrations.AddField(
            model_name='anticipo',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='get_anticipo', to='pagos.Empresa', verbose_name='Factura'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='anticipo',
            name='factura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='get_anticipo', to='pagos.factura', verbose_name='Factura'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='retiva',
            field=models.IntegerField(choices=[(0, 0), (75, 75), (100, 100)], default=75, verbose_name='Retención IVA'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='rif',
            field=models.CharField(max_length=150, verbose_name='RIF'),
        ),
    ]
