# Generated by Django 2.2.2 on 2020-07-09 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=150, verbose_name='Apellido')),
                ('cedula', models.IntegerField(verbose_name='Cédula')),
                ('cargo', models.CharField(max_length=150, verbose_name='Cargo')),
                ('departamento', models.CharField(max_length=150, verbose_name='Departamento')),
                ('entrada', models.TimeField(verbose_name='entrada')),
                ('salida', models.TimeField(verbose_name='Salida')),
            ],
        ),
        migrations.CreateModel(
            name='horas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrada', models.TimeField(auto_now=True, verbose_name='Entrada')),
                ('salida', models.TimeField(blank=True, null=True, verbose_name='Salida')),
                ('fecha', models.DateField(auto_now=True, verbose_name='Fecha')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Trabajador', verbose_name='Trabajador')),
            ],
        ),
    ]
