# Generated by Django 2.2 on 2021-03-02 15:49

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='visitantes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('cedula', models.IntegerField(verbose_name='Cédula')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='fecha')),
                ('tipo', models.CharField(choices=[('E', 'Entrada'), ('S', 'Salida')], default='E', max_length=1, verbose_name='Tipo')),
                ('observacion', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registration.departamento', verbose_name='Departamento')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='get_user_v', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='permisos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desde', models.DateTimeField()),
                ('hasta', models.DateTimeField()),
                ('motivo', models.CharField(choices=[('P', 'Permiso'), ('V', 'Vacaciones'), ('R', 'Reposo'), ('O', 'Otro')], default='P', max_length=1)),
                ('observacion', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('archivo', models.FileField(blank=True, null=True, upload_to=core.models.user_directory_path)),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='get_trabajador', to='registration.Trabajador', verbose_name='Trabajador')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='get_usuario', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='marca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='fecha')),
                ('tipo', models.CharField(choices=[('E', 'Entrada'), ('S', 'Salida')], default='E', max_length=1)),
                ('modo', models.CharField(choices=[('R', 'Regular'), ('G', 'Guardia')], default='R', max_length=1)),
                ('observacion', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registration.Trabajador', verbose_name='Trabajador')),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='guardia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrada', models.DateTimeField()),
                ('salida', models.DateTimeField()),
                ('observacion', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registration.Trabajador', verbose_name='Trabajador')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='get_user_g', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='extras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrada', models.DateTimeField()),
                ('salida', models.DateTimeField()),
                ('observacion', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.Trabajador', verbose_name='Trabajador')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='get_user', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
    ]
