# Generated by Django 2.2 on 2021-03-03 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permisos',
            name='desde',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='permisos',
            name='hasta',
            field=models.DateField(),
        ),
    ]
