# Generated by Django 2.2 on 2021-03-04 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210303_0007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marca',
            name='modo',
        ),
    ]
