# Generated by Django 2.2.2 on 2020-07-09 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200709_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horas',
            name='entrada',
            field=models.TimeField(auto_now_add=True, verbose_name='Entrada'),
        ),
    ]
