# Generated by Django 2.2 on 2021-03-12 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_supervisor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitantes',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='get_user_v', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
