# Generated by Django 2.2 on 2021-04-27 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210422_2327'),
        ('core', '0003_auto_20210312_1218'),
    ]

    operations = [
    ]
