# Generated by Django 2.2 on 2021-05-03 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_merge_20210427_0104'),
        ('core', '0004_merge_20210423_1645'),
    ]

    operations = [
    ]
