# Generated by Django 2.2.2 on 2020-07-10 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200709_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajador',
            name='codigo',
            field=models.IntegerField(blank=True, null=True, verbose_name='Código'),
        ),
    ]
