# Generated by Django 2.2 on 2021-02-26 01:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_trabajador_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='marca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='fecha')),
                ('tipo', models.CharField(choices=[('E', 'Entrada'), ('S', 'Salida')], default='E', max_length=2)),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Trabajador')),
            ],
        ),
        migrations.DeleteModel(
            name='horas',
        ),
        migrations.DeleteModel(
            name='Trabajador',
        ),
    ]
