# Generated by Django 2.2 on 2021-02-26 01:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0007_auto_20210225_2136'),
    ]

    operations = [
        migrations.CreateModel(
            name='guardia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrada', models.TimeField()),
                ('salida', models.TimeField()),
                ('fecha', models.DateField()),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Trabajador')),
            ],
        ),
    ]
