# Generated by Django 2.2 on 2021-02-26 03:50

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0008_guardia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marca',
            options={'ordering': ['-pk']},
        ),
        migrations.CreateModel(
            name='permisos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desde', models.DateTimeField()),
                ('hasta', models.DateTimeField()),
                ('motivo', models.CharField(choices=[('P', 'Permiso'), ('V', 'Vacaciones'), ('R', 'Reposo'), ('O', 'Otro')], default='P', max_length=1)),
                ('observacion', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('archivo', models.FileField(blank=True, null=True, upload_to=core.models.user_directory_path)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_usuario', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_trabajador', to=settings.AUTH_USER_MODEL, verbose_name='Trabajador')),
            ],
        ),
    ]
