# Generated by Django 2.2 on 2021-02-26 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210225_2350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permisos',
            old_name='User',
            new_name='user',
        ),
    ]
