# Generated by Django 2.2 on 2021-02-26 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210225_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='marca',
            name='modo',
            field=models.CharField(choices=[('E', 'Entrada'), ('S', 'Salida')], default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='marca',
            name='tipo',
            field=models.CharField(choices=[('E', 'Entrada'), ('S', 'Salida')], default='E', max_length=1),
        ),
    ]
