# Generated by Django 2.2 on 2021-02-26 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210226_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marca',
            name='modo',
            field=models.CharField(choices=[('R', 'Regular'), ('G', 'Guardia')], default='R', max_length=1),
        ),
    ]
