# Generated by Django 2.2 on 2021-02-26 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20210226_0407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guardia',
            name='entrada',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='guardia',
            name='salida',
            field=models.DateTimeField(),
        ),
    ]
