# Generated by Django 2.2 on 2021-02-26 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20210225_2240'),
        ('core', '0016_auto_20210226_0408'),
    ]

    operations = [
        migrations.CreateModel(
            name='visitantes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('cedula', models.IntegerField(verbose_name='Cédula')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='fecha')),
                ('tipo', models.CharField(choices=[('E', 'Entrada'), ('S', 'Salida')], default='E', max_length=1)),
                ('observacion', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.departamento', verbose_name='Departamento')),
            ],
        ),
    ]
