# Generated by Django 2.2 on 2021-02-28 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_visitantes'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitantes',
            name='apellido',
            field=models.CharField(default='', max_length=100, verbose_name='Apellido'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='visitantes',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
    ]
