# Generated by Django 2.2 on 2021-03-01 00:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0018_auto_20210228_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitantes',
            name='tipo',
            field=models.CharField(choices=[('E', 'Entrada'), ('S', 'Salida')], default='E', max_length=1, verbose_name='Tipo'),
        ),
        migrations.CreateModel(
            name='extras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrada', models.DateTimeField()),
                ('salida', models.DateTimeField()),
                ('observacion', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Trabajador')),
            ],
        ),
    ]
