# Generated by Django 2.2 on 2021-03-01 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0019_auto_20210301_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='extras',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='get_user', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='guardia',
            name='trabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Trabajador'),
        ),
        migrations.AlterField(
            model_name='marca',
            name='trabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Trabajador'),
        ),
        migrations.AlterField(
            model_name='permisos',
            name='trabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='get_trabajador', to=settings.AUTH_USER_MODEL, verbose_name='Trabajador'),
        ),
        migrations.AlterField(
            model_name='permisos',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='get_usuario', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='visitantes',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registration.departamento', verbose_name='Departamento'),
        ),
    ]
