# Generated by Django 2.2 on 2021-03-04 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trabajador',
            options={'ordering': ['cedula'], 'verbose_name': 'trabajador', 'verbose_name_plural': 'trabajadores'},
        ),
    ]
