# Generated by Django 2.2 on 2021-03-08 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajador',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='codigo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Código'),
        ),
    ]
