# Generated by Django 2.2 on 2021-02-26 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='guardia',
        ),
    ]
