# Generated by Django 2.2 on 2021-02-26 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_delete_guardia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.departamento', verbose_name='Departamento'),
        ),
    ]
